from sklearn.feature_extraction.text import CountVectorizer

IGNORED = {
    "articles": ["a", "an", "the"],
    "conjunctions": [
        "for",
        "and",
        "nor",
        "but",
        "or",
        "yet",
        "so",
        "either",
        "neither",
        "both",
        "whether",
        "because",
        "although",
        "since",
        "if",
        "unless",
        "while",
        "before",
        "after",
        "though",
        "as",
        "whereas",
        "when",
        "until",
        "that",
        "however",
        "therefore",
        "moreover",
        "consequently",
        "furthermore",
        "nevertheless",
        "meanwhile",
        "thus",
    ],
    "prepositions": [
        "aboard",
        "about",
        "above",
        "absent",
        "across",
        "after",
        "against",
        "along",
        "alongside",
        "amid",
        "amidst",
        "among",
        "amongst",
        "around",
        "as",
        "at",
        "atop",
        "bar",
        "barring",
        "before",
        "behind",
        "below",
        "beneath",
        "beside",
        "besides",
        "between",
        "beyond",
        "but",
        "by",
        "circa",
        "concerning",
        "counting",
        "despite",
        "down",
        "during",
        "effective",
        "except",
        "excepting",
        "excluding",
        "failing",
        "following",
        "for",
        "from",
        "in",
        "including",
        "inside",
        "into",
        "less",
        "like",
        "minus",
        "near",
        "next",
        "notwithstanding",
        "of",
        "off",
        "on",
        "onto",
        "opposite",
        "out",
        "outside",
        "over",
        "past",
        "pending",
        "per",
        "plus",
        "regarding",
        "respecting",
        "short",
        "since",
        "than",
        "through",
        "throughout",
        "to",
        "toward",
        "towards",
        "under",
        "underneath",
        "unlike",
        "until",
        "up",
        "upon",
        "versus",
        "vs",
        "via",
        "wanting",
        "with",
        "within",
        "without",
        "worth",
    ],
    "auxiliaries": [
        "is",
        "are",
        "be",
        "do",
        "have",
        "can",
        "could",
        "dare",
        "may",
        "might",
        "must",
        "should",
        "will",
        "would",
    ],
    "pronouns": [
        "i",
        "me",
        "you",
        "they",
        "them",
        "he",
        "him",
        "she",
        "her",
        "it",
        "we",
        "us",
        "that",
        "what",
        "which",
        "who",
        "whom",
        "whose",
        "this",
        "that",
        "these",
        "those",
        "another",
        "any",
        "anybody",
        "anyone",
        "anything",
        "both",
        "each",
        "either",
        "everybody",
        "everyone",
        "everything",
        "neither",
        "nobody",
        "none",
        "noone",
        "one",
        "other",
        "some",
        "somebody",
        "someone",
        "such",
        "myself",
        "yourself",
        "yourselves",
        "themself",
        "themselves",
        "herself",
        "himself",
        "oneself",
        "itself",
        "ourselves",
        "myself",
        "yourself",
        "yourselves",
        "themself",
        "themselves",
        "herself",
        "himself",
        "oneself",
        "itself",
        "ourselves",
        "mine",
        "your",
        "yours",
        "theirs",
        "his",
        "hers",
        "its",
        "ours",
        "what",
        "which",
        "who",
        "whose",
        "eachother",
        "oneanother",
        "either",
        "each",
        "neither",
        "any",
        "none",
    ],
}

NGRAM_MAX = 2


def vectorize(text):
    """Vectorizes the given text using sklearn's CountVectorizer."""
    corpus = [text]
    vectorizer = CountVectorizer(
        ngram_range=(1, NGRAM_MAX), token_pattern=r"\b\w+\b", min_df=1
    )
    X = vectorizer.fit_transform(corpus)
    labels, values = rank_terms(vectorizer, X)
    return labels, values


def rank_terms(vectorizer, X):
    """Return repeated, non-ignored terms ordered by descending frequency."""
    feature_names = vectorizer.get_feature_names_out()
    counts = X.toarray().flatten().astype(int).tolist()
    features = sorted(
        [
            feature
            for feature in zip(feature_names, counts)
            if feature[1] > 1 and feature[0] not in ignored_tokens()
        ],
        key=lambda feature: feature[1],
        reverse=True,
    )
    return zip(*features)


def ignored_tokens(ngram_max=NGRAM_MAX):
    """Return a set of ignored phrases"""
    result = set()
    words = list(set().union(*IGNORED.values()))
    for n in range(ngram_max):
        ngram = n + 1
        if ngram == 1:
            phrases = set(words)
        else:
            phrases = {f"{phrase} {word}" for phrase in phrases for word in words}
        result.update(phrases)
    return result
